# -*- coding: utf-8 -*-
"""Review_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135_TICZdwj9QN1vCQJq4Vxmx-nRLJKt1
"""

import re
import requests
import csv
from bs4 import BeautifulSoup

def validate_amazon_url(url):
    pattern = r"(https?://)?(www\.)?amazon\.(com|in|co\.uk|de|ca|fr|co\.jp|it|es|nl|com\.mx|com\.au|com\.br|ae|sg|sa)/.*"
    return bool(re.match(pattern, url))

def fetch_amazon_data(product_link):
    if not validate_amazon_url(product_link):
        raise ValueError("Invalid Amazon product URL.")

    request_headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Referer': 'https://www.google.com/',
    }

    response = requests.get(product_link, headers=request_headers)
    if response.status_code == 200:
        page_content = BeautifulSoup(response.text, 'html.parser')

        # Extract customer reviews
        extracted_reviews = []
        for entry in page_content.select('.review'):
            review_body = entry.select_one('.review-text').text.strip() if entry.select_one('.review-text') else None
            if review_body:
                extracted_reviews.append([review_body])

        # Save reviews to CSV file
        with open("Amazon_Reviews.csv", "w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["Review Content"])
            writer.writerows(extracted_reviews)
    else:
        print("Error: Unable to retrieve data. HTTP Status Code:", response.status_code)

if __name__ == "__main__":
    # Execution
    try:
        product_url = input("Enter Amazon product URL: ")
        # if user's link wil not worked then use it: "https://www.amazon.in/gp/aw/d/B01EUQJNFM/?_encoding=UTF8&pd_rd_plhdr=t&aaxitk=62ca1e6879ebd69f0c8492437787fe60&hsa_cr_id=2641126020602&sr=1-1-undefined&ref_=sbx_be_dp_arbies_lsi4d_asin_0_img&pd_rd_w=SiJeF&content-id=amzn1.sym.8b13584a-c7fa-402c-b0a3-ddf39b989f1f&pf_rd_p=8b13584a-c7fa-402c-b0a3-ddf39b989f1f&pf_rd_r=TVPQRE0G34YBJ1WSRM24&pd_rd_wg=IPENb&pd_rd_r=a4b594ff-2492-48b6-839a-56af5ea13d33&th=1&psc=1"
        fetch_amazon_data(product_url)
        print("Reviews saved to Amazon_Reviews.csv")
    except ValueError as err:
        print(err)